"""
Seed de la tabla lineups a partir del contenido REAL que ya vive hardcodeado
en frontend/src/views/LineUps.tsx (const LINEUPS). Transcripción manual, no
hay parser de TSX acá -- si se agregan/editan entradas en el frontend, este
seed hay que actualizarlo a mano (o migrar LineUps.tsx a consumir GET
/lineups en vez de su propio array, momento en el que este script pasa a ser
la única fuente).

Idempotente: borra y reinserta todo el mapa que trae, mismo patrón que
PlayerProfileTag/GlobalMetricStats (cache reconstruible, no fuente de
verdad manual).

Uso:
    python scripts/seed_lineups.py
"""

from __future__ import annotations

import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import delete
from sqlalchemy.orm import Session

from cs2tracker.db import Lineup, get_engine, init_db

# team=None sería "sirve para ambos lados" -- no se usa todavía, cada
# entrada de LineUps.tsx ya trae side T o CT explícito.
MIRAGE_LINEUPS: list[dict] = [
    # ---- CT ----
    dict(
        category="he",
        team="CT",
        label="Caverna",
        x=0.44,
        y=0.23,
        video_url="cs2-lineups/MIRAGE/MIRAGE-CT/deto-ct-caverna.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Caverna",
        x=0.46,
        y=0.25,
        video_url="cs2-lineups/MIRAGE/MIRAGE-CT/moli-ct-caverna.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Tapete",
        x=0.22,
        y=0.31,
        video_url="cs2-lineups/MIRAGE/MIRAGE-CT/moli-ct-tapete.mp4",
    ),
    dict(
        category="flash",
        team="CT",
        label="Mid",
        x=0.5,
        y=0.38,
        video_url="cs2-lineups/MIRAGE/MIRAGE-CT/popflash-cd-mid.mp4",
    ),
    dict(
        category="flash",
        team="CT",
        label="Medio",
        x=0.56,
        y=0.46,
        video_url="cs2-lineups/MIRAGE/MIRAGE-CT/popflash-ct-medio.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Zona L",
        x=0.62,
        y=0.42,
        video_url="cs2-lineups/MIRAGE/MIRAGE-CT/smoke-ct-L.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Spawn Palace",
        x=0.68,
        y=0.23,
        video_url="cs2-lineups/MIRAGE/MIRAGE-CT/smoke-ct-spawnPalace.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Tapete",
        x=0.24,
        y=0.33,
        video_url="cs2-lineups/MIRAGE/MIRAGE-CT/smoke-ct-tapete.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Tapete / Spawn",
        x=0.45,
        y=0.19,
        video_url="cs2-lineups/MIRAGE/MIRAGE-CT/smoke-ct-tapetespawn.mp4",
    ),
    # ---- T ----
    dict(
        category="molotov",
        team="T",
        label="A - Arena oscura",
        x=0.16,
        y=0.25,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/moli-A-arenaoscuro.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Mid",
        x=0.54,
        y=0.48,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/moli-mid.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Van",
        x=0.46,
        y=0.64,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/moli-van.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="A",
        x=0.235,
        y=0.285,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/popflash-A.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="B",
        x=0.56,
        y=0.765,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/popflash-b.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Mid",
        x=0.52,
        y=0.44,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/popflash-mid.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="L Wall",
        x=0.474,
        y=0.327,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/smoke-Lwall.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="B Window",
        x=0.253,
        y=0.387,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/smoke-b-window.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Cabecinha",
        x=0.541,
        y=0.642,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/smoke-cabecinha.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Forest",
        x=0.149,
        y=0.242,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/smoke-forest.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Jungle",
        x=0.393,
        y=0.567,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/smoke-jungle.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Liga",
        x=0.501,
        y=0.499,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/smoke-liga.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Short / Mid",
        x=0.518,
        y=0.416,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/smoke-short-mid.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Tickets CT",
        x=0.453,
        y=0.797,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/smoke-ticketsCT.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Ventana",
        x=0.414,
        y=0.454,
        video_url="cs2-lineups/MIRAGE/MIRAGE-TT/smoke-ventana.mp4",
    ),
]

# Los 4 mapas de abajo (Cache/Dust2/Inferno/Nuke) se generaron parseando el
# listado real del bucket R2 (categoría y equipo salen del nombre de archivo:
# deto/flash/moli/smoke- + ct/tt-, "cttt" = sirve a ambos lados, "retake" =
# setup de retake CT sin equipo explícito en el nombre). x/y quedan en 0.5/0.5
# (centro, placeholder) -- el overlay no las usa (es lista, no minimapa), pero
# el explorador web sí -- falta posicionarlas con LineupCoordEditor el día que
# ese explorador consuma la API real en vez de mockLineups.ts.
CACHE_LINEUPS: list[dict] = [
    dict(
        category="he",
        team="T",
        label="Backside B",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/deto-tt-backsideB.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Garage",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/flash-tt-garage.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Lona",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/moli-ct-lona.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Lona 2",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/moli-ct-lona2.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Backside B",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/moli-tt-backsideB.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Default Headshot B",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/moli-tt-default-headshotB.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Medio Cemento",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/moli-tt-mediocemento.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Mulita",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/moli-tt-mulita.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Site B Toxico",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/moli-tt-siteBToxico.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Sunroom Headshoot",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/moli-tt-sunroomHeadshoot.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Basura Conector",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-ct-basura-conector.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Garage Basect",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-ct-garage-basect.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Garage Toyota",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-ct-garage-toyota.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Garage A",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-ct-garageA.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Main B",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-ct-mainB.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Mid Spawn 1",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-ct-mid-spawn1.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Mid Spawn 2",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-ct-mid-spawn2.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Mid Spawn 3",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-ct-mid-spawn3.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Mid Spawn 4",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-ct-mid-spawn4.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Afu Azul",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-afu-azul.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Calle",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-calle.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="CT",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-ct.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Default A",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-defaultA.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Heaven Easy",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-heavenEasy.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Heaven Hard",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-heavenHard.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Left Mid",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-leftMid.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Main B",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-mainB.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Mid",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-mid.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Right Mid",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-rightMid.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Roja",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-roja.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Site B",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-siteB.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Site Caja",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-siteCaja.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Site Caja A",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-siteCajaA.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Solo Combination",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/CACHE/smoke-tt-soloCombination.mp4",
    ),
]

DUST2_LINEUPS: list[dict] = [
    dict(
        category="flash",
        team="T",
        label="Baranda",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/flash-tt-baranda.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Baranda Oscuro",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/flash-tt-barandaOscuro.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Fondo",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/flash-tt-fondo.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Larga",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/flash-tt-larga.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Puerta Fondo",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/flash-tt-puertaFondo.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Site A",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/flash-tt-siteA.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Baranda",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/moli-ct-baranda.mp4",
    ),
    dict(
        category="molotov",
        team=None,
        label="Site A Desde Rampa",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/moli-cttt-siteA-desdeRampa.mp4",
    ),
    dict(
        category="molotov",
        team=None,
        label="Site A",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/moli-cttt-siteA.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Arena Ninja (Retake)",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/moli-retake-arenaNinja.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Caja B (Retake)",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/moli-retake-cajaB.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Cat (Retake)",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/moli-retake-cat.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Site B (Retake)",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/moli-retake-siteB.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Fondo",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-ct-fondo.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Fondo 2",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-ct-fondo2.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Medio Spawn",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-ct-mediospawn.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Mid",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-ct-mid.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Oscuro",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-ct-oscuro.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Previa Oscuro",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-ct-previaoscuro.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Puerta Avanzado",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-ct-puertaavanzado.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Suicida",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-ct-suicida.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Caja Mid",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-CajaMid.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Auto",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-auto.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Baranda",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-baranda.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="CT Mid",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-ct-mid.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Entry Oscuro",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-entryOscuro.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Long",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-long.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Puerta Baranda",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-puerta-baranda.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Puerta Previa Oscuro",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-puerta-previaOscuro.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Puerta Oscuro",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-puertaOscuro.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Puerta Oscuro 2",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-puertaOscuro2.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Puerta Long",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-puertalong.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Rampa CT",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-rampaCT.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Spawn Mid",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-spawnMID.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Uper B",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-uperB.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Ventana Previa Oscuro",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-ventana-previaOscuro.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Ventana B",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/DUST 2/smoke-tt-ventanaB.mp4",
    ),
]

INFERNO_LINEUPS: list[dict] = [
    dict(
        category="he",
        team="T",
        label="Triple",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/deto-tt-triple.mp4",
    ),
    dict(
        category="flash",
        team="CT",
        label="Arena",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/flash-ct-arena.mp4",
    ),
    dict(
        category="flash",
        team="CT",
        label="Banana",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/flash-ct-banana.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Banana",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/flash-tt-banana.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Long A",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/flash-tt-longA.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Mid",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/flash-tt-mid.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Short",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/flash-tt-short.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Tapete",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/flash-tt-tapete.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Banana",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/moli-ct-banana.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Default Retake",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/moli-ct-default-retake.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Ataud",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/moli-tt-ataud.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Default",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/moli-tt-default.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Oscuro B",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/moli-tt-oscuroB.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Tripleeasy",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/moli-tt-tripleeasy.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Triplepro",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/moli-tt-triplepro.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Arena Retake",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/smoke-ct-arena-retake.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Banana Spawn",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/smoke-ct-banana-spawn.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Banana Retake",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/smoke-ct-banana.-retake.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Medio Spawn",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/smoke-ct-medio.spawn.mp4",
    ),
    dict(
        category="smoke",
        team="CT",
        label="Mid Spawn",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/smoke-ct-mid-spawn.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Arco Vino Oneguy",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/INFERNO/smoke-tt-arcoVino-oneguy.mp4",
    ),
]

NUKE_LINEUPS: list[dict] = [
    dict(
        category="he",
        team="CT",
        label="Radio",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/deto-ct-radio.mp4",
    ),
    dict(
        category="he",
        team="CT",
        label="Radio 2",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/deto-ct-radio2.mp4",
    ),
    dict(
        category="he",
        team="T",
        label="Metal",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/deto-tt-metal.mp4",
    ),
    dict(
        category="he",
        team="T",
        label="Roja",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/deto-tt-roja.mp4",
    ),
    dict(
        category="flash",
        team="CT",
        label="Ducto",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/flash-ct-ducto.mp4",
    ),
    dict(
        category="flash",
        team="CT",
        label="Heaven 1",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/flash-ct-heaven1.mp4",
    ),
    dict(
        category="flash",
        team="CT",
        label="Heaven 2",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/flash-ct-heaven2.mp4",
    ),
    dict(
        category="flash",
        team="CT",
        label="Heaven 3",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/flash-ct-heaven3.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Rampa",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/flash-tt-rampa.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Site 3",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/flash-tt-site3.mp4",
    ),
    dict(
        category="flash",
        team="T",
        label="Site A",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/flash-tt-siteA.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Default A",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-ct-defaultA.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Ducto",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-ct-ducto.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Kz",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-ct-kz.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Medio",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-ct-medio.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Silo",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-ct-silo.mp4",
    ),
    dict(
        category="molotov",
        team="CT",
        label="Taxi",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-ct-taxi.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Cielo",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-tt-cielo.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Falso Ducto",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-tt-falsoducto.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Kz 1",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-tt-kz1.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Kz 2",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-tt-kz2.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Kz 3",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-tt-kz3.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Rafters",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-tt-rafters.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Roja",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-tt-roja.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Secret",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-tt-secret.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Site A Default",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-tt-siteA-default.mp4",
    ),
    dict(
        category="molotov",
        team="T",
        label="Site A Default 2",
        x=0.5,
        y=0.5,
        video_url="cs2-lineups/NUKE/moli-tt-siteA-default2.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Afue 1",
        x=0.382,
        y=0.584,
        video_url="cs2-lineups/NUKE/smoke-tt-afue1.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Afue 2",
        x=0.302,
        y=0.582,
        video_url="cs2-lineups/NUKE/smoke-tt-afue2.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Cielo A",
        x=0.497,
        y=0.605,
        video_url="cs2-lineups/NUKE/smoke-tt-cieloA.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Ducto Spawn",
        x=0.316,
        y=0.528,
        video_url="cs2-lineups/NUKE/smoke-tt-ducto-spawn.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Ductos Spawn 2",
        x=0.363,
        y=0.535,
        video_url="cs2-lineups/NUKE/smoke-tt-ductos-spawn2.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Garage Spawn",
        x=0.356,
        y=0.545,
        video_url="cs2-lineups/NUKE/smoke-tt-garage-spawn.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Garage 2",
        x=0.437,
        y=0.681,
        video_url="cs2-lineups/NUKE/smoke-tt-garage2.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Garage Afue",
        x=0.384,
        y=0.574,
        video_url="cs2-lineups/NUKE/smoke-tt-garageAfue.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Lockers",
        x=0.298,
        y=0.536,
        video_url="cs2-lineups/NUKE/smoke-tt-lockers.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Lockers 2",
        x=0.349,
        y=0.523,
        video_url="cs2-lineups/NUKE/smoke-tt-lockers2.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Lockers 3",
        x=0.464,
        y=0.704,
        video_url="cs2-lineups/NUKE/smoke-tt-lockers3.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Pasaje Lockers",
        x=0.47,
        y=0.676,
        video_url="cs2-lineups/NUKE/smoke-tt-pasajeLockers.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Rampa",
        x=0.514,
        y=0.478,
        video_url="cs2-lineups/NUKE/smoke-tt-rampa.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Rampa Profunda",
        x=0.513,
        y=0.455,
        video_url="cs2-lineups/NUKE/smoke-tt-rampaprofunda.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Roja",
        x=0.444,
        y=0.661,
        video_url="cs2-lineups/NUKE/smoke-tt-roja.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Roja Secret",
        x=0.661,
        y=0.738,
        video_url="cs2-lineups/NUKE/smoke-tt-rojaSecret.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Roja Secret 2",
        x=0.371,
        y=0.574,
        video_url="cs2-lineups/NUKE/smoke-tt-rojaSecret2.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Roja Secret 3",
        x=0.429,
        y=0.653,
        video_url="cs2-lineups/NUKE/smoke-tt-rojaSecret3.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Secret Roja 1",
        x=0.31,
        y=0.565,
        video_url="cs2-lineups/NUKE/smoke-tt-secretRoja1.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Secret Roja 2",
        x=0.337,
        y=0.558,
        video_url="cs2-lineups/NUKE/smoke-tt-secretRoja2.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Secret Roja 3",
        x=0.37,
        y=0.586,
        video_url="cs2-lineups/NUKE/smoke-tt-secretRoja3.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Secret Roja 4",
        x=0.437,
        y=0.666,
        video_url="cs2-lineups/NUKE/smoke-tt-secretRoja4.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Taxi Afu",
        x=0.451,
        y=0.68,
        video_url="cs2-lineups/NUKE/smoke-tt-taxi-afu.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Taxi 1",
        x=0.464,
        y=0.443,
        video_url="cs2-lineups/NUKE/smoke-tt-taxi1.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Taxi 2",
        x=0.482,
        y=0.445,
        video_url="cs2-lineups/NUKE/smoke-tt-taxi2.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Taxi Rooft Spawn",
        x=0.244,
        y=0.582,
        video_url="cs2-lineups/NUKE/smoke-tt-taxiRooft-spawn.mp4",
    ),
    dict(
        category="smoke",
        team="T",
        label="Taxi Rooft",
        x=0.298,
        y=0.546,
        video_url="cs2-lineups/NUKE/smoke-tt-taxiRooft.mp4",
    ),
]

SEED_BY_MAP: dict[str, list[dict]] = {
    "de_mirage": MIRAGE_LINEUPS,
    "de_cache": CACHE_LINEUPS,
    "de_dust2": DUST2_LINEUPS,
    "de_inferno": INFERNO_LINEUPS,
    "de_nuke": NUKE_LINEUPS,
}


def seed() -> None:
    init_db()
    now = datetime.now(UTC).isoformat()
    with Session(get_engine()) as s:
        for map_key, entries in SEED_BY_MAP.items():
            s.execute(delete(Lineup).where(Lineup.map == map_key))
            for entry in entries:
                s.add(Lineup(map=map_key, created_at=now, **entry))
            print(f"[seed_lineups] {map_key}: {len(entries)} lineups")
        s.commit()


if __name__ == "__main__":
    seed()
