"""add rating

Revision ID: 0196a1b8bb1d
Revises: 9b8e994770af
Create Date: 2026-07-13 19:57:49.788699
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0196a1b8bb1d"
down_revision: str | None = "9b8e994770af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_match_stats", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rating", sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_match_stats", schema=None) as batch_op:
        batch_op.drop_column("rating")

    # ### end Alembic commands ###
