"""esquema inicial

Revision ID: 0ed19b7a686e
Revises:
Create Date: 2026-07-13 14:47:37.615880
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0ed19b7a686e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("map", sa.String(), nullable=True),
        sa.Column("demo_file", sa.String(), nullable=False),
        sa.Column("tickrate", sa.Integer(), nullable=True),
        sa.Column("n_rounds", sa.Integer(), nullable=True),
        sa.Column("ingested_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("match_id"),
    )
    op.create_table(
        "players",
        sa.Column("steamid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("steamid"),
    )
    op.create_table(
        "damages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("round_num", sa.Integer(), nullable=True),
        sa.Column("tick", sa.Integer(), nullable=True),
        sa.Column("attacker", sa.String(), nullable=True),
        sa.Column("victim", sa.String(), nullable=False),
        sa.Column("weapon", sa.String(), nullable=True),
        sa.Column("dmg_health", sa.Integer(), nullable=True),
        sa.Column("dmg_armor", sa.Integer(), nullable=True),
        sa.Column("hitgroup", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.match_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("damages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_damages_match_id"), ["match_id"], unique=False)

    op.create_table(
        "kills",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("round_num", sa.Integer(), nullable=True),
        sa.Column("tick", sa.Integer(), nullable=True),
        sa.Column("attacker", sa.String(), nullable=True),
        sa.Column("victim", sa.String(), nullable=False),
        sa.Column("assister", sa.String(), nullable=True),
        sa.Column("weapon", sa.String(), nullable=True),
        sa.Column("headshot", sa.Boolean(), nullable=True),
        sa.Column("penetrated", sa.Boolean(), nullable=True),
        sa.Column("noscope", sa.Boolean(), nullable=True),
        sa.Column("thru_smoke", sa.Boolean(), nullable=True),
        sa.Column("attacker_blind", sa.Boolean(), nullable=True),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column("attacker_x", sa.Float(), nullable=True),
        sa.Column("attacker_y", sa.Float(), nullable=True),
        sa.Column("attacker_z", sa.Float(), nullable=True),
        sa.Column("victim_x", sa.Float(), nullable=True),
        sa.Column("victim_y", sa.Float(), nullable=True),
        sa.Column("victim_z", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.match_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("kills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kills_match_id"), ["match_id"], unique=False)

    op.create_table(
        "match_players",
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("steamid", sa.String(), nullable=False),
        sa.Column("team_num", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.match_id"],
        ),
        sa.ForeignKeyConstraint(
            ["steamid"],
            ["players.steamid"],
        ),
        sa.PrimaryKeyConstraint("match_id", "steamid"),
    )
    op.create_table(
        "player_match_stats",
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("steamid", sa.String(), nullable=False),
        sa.Column("kills", sa.Integer(), nullable=False),
        sa.Column("deaths", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("damage", sa.Integer(), nullable=False),
        sa.Column("adr", sa.Float(), nullable=False),
        sa.Column("kd", sa.Float(), nullable=False),
        sa.Column("hs_pct", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.match_id"],
        ),
        sa.ForeignKeyConstraint(
            ["steamid"],
            ["players.steamid"],
        ),
        sa.PrimaryKeyConstraint("match_id", "steamid"),
    )
    op.create_table(
        "rounds",
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("round_num", sa.Integer(), nullable=False),
        sa.Column("end_tick", sa.Integer(), nullable=True),
        sa.Column("winner_num", sa.Integer(), nullable=True),
        sa.Column("win_reason", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.match_id"],
        ),
        sa.PrimaryKeyConstraint("match_id", "round_num"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rounds")
    op.drop_table("player_match_stats")
    op.drop_table("match_players")
    with op.batch_alter_table("kills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kills_match_id"))

    op.drop_table("kills")
    with op.batch_alter_table("damages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_damages_match_id"))

    op.drop_table("damages")
    op.drop_table("players")
    op.drop_table("matches")
    # ### end Alembic commands ###
