"""add login_events table

Revision ID: 498146ec5f38
Revises: f00cb11147dc
Create Date: 2026-08-06 11:25:18.383911
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "498146ec5f38"
down_revision: str | None = "f00cb11147dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("occurred_at", sa.String(), nullable=False),
        sa.Column("steamid", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["steamid"],
            ["players.steamid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("login_events", schema=None) as batch_op:
        batch_op.create_index("idx_login_events_ip_time", ["ip", "occurred_at"], unique=False)
        batch_op.create_index(
            "idx_login_events_steamid_time", ["steamid", "occurred_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("login_events", schema=None) as batch_op:
        batch_op.drop_index("idx_login_events_steamid_time")
        batch_op.drop_index("idx_login_events_ip_time")

    op.drop_table("login_events")
    # ### end Alembic commands ###
