"""add trade kill attribution to player_map_events

Revision ID: 4d6cde1f551d
Revises: 51d78414f696
Create Date: 2026-07-15 04:35:20.204629
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "4d6cde1f551d"
down_revision: str | None = "51d78414f696"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_map_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_trade_kill", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("avenged_steamid", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_map_events", schema=None) as batch_op:
        batch_op.drop_column("avenged_steamid")
        batch_op.drop_column("is_trade_kill")

    # ### end Alembic commands ###
