"""add rank to match_players

Revision ID: 4f8498400f9a
Revises: ddedba0a290d
Create Date: 2026-07-17 01:39:08.911726
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "4f8498400f9a"
down_revision: str | None = "ddedba0a290d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("match_players", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rank", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("rank_type", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("comp_wins", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("match_players", schema=None) as batch_op:
        batch_op.drop_column("comp_wins")
        batch_op.drop_column("rank_type")
        batch_op.drop_column("rank")

    # ### end Alembic commands ###
