"""users grenades blinds player map events zones

Revision ID: 51d78414f696
Revises: 0196a1b8bb1d
Create Date: 2026-07-14 19:16:22.777192
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "51d78414f696"
down_revision: str | None = "0196a1b8bb1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_map_zones",
        sa.Column("steamid", sa.String(), nullable=False),
        sa.Column("map", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("grid_x", sa.Integer(), nullable=False),
        sa.Column("grid_y", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("entry_count", sa.Integer(), nullable=False),
        sa.Column("traded_count", sa.Integer(), nullable=False),
        sa.Column("top_weapon", sa.String(), nullable=True),
        sa.Column("avg_enemies_blinded", sa.Float(), nullable=True),
        sa.Column("total_blind_duration", sa.Float(), nullable=True),
        sa.Column("avg_damage", sa.Float(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["steamid"],
            ["players.steamid"],
        ),
        sa.PrimaryKeyConstraint("steamid", "map", "event_type", "grid_x", "grid_y"),
    )
    op.create_table(
        "users",
        sa.Column("steamid", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("last_login_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["steamid"],
            ["players.steamid"],
        ),
        sa.PrimaryKeyConstraint("steamid"),
    )
    op.create_table(
        "blinds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("round_num", sa.Integer(), nullable=True),
        sa.Column("tick", sa.Integer(), nullable=True),
        sa.Column("attacker", sa.String(), nullable=True),
        sa.Column("victim", sa.String(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.match_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("blinds", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blinds_match_id"), ["match_id"], unique=False)

    op.create_table(
        "grenades",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("round_num", sa.Integer(), nullable=True),
        sa.Column("tick", sa.Integer(), nullable=True),
        sa.Column("thrower", sa.String(), nullable=True),
        sa.Column("weapon", sa.String(), nullable=True),
        sa.Column("x", sa.Float(), nullable=True),
        sa.Column("y", sa.Float(), nullable=True),
        sa.Column("z", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.match_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("grenades", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_grenades_match_id"), ["match_id"], unique=False)

    op.create_table(
        "player_map_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("round_num", sa.Integer(), nullable=True),
        sa.Column("tick", sa.Integer(), nullable=True),
        sa.Column("steamid", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("is_entry", sa.Boolean(), nullable=False),
        sa.Column("is_traded", sa.Boolean(), nullable=True),
        sa.Column("map", sa.String(), nullable=False),
        sa.Column("team_num", sa.Integer(), nullable=True),
        sa.Column("round_won", sa.Boolean(), nullable=True),
        sa.Column("weapon", sa.String(), nullable=True),
        sa.Column("headshot", sa.Boolean(), nullable=True),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column("enemies_blinded", sa.Integer(), nullable=True),
        sa.Column("blind_duration_total", sa.Float(), nullable=True),
        sa.Column("teammates_blinded", sa.Integer(), nullable=True),
        sa.Column("damage_dealt", sa.Integer(), nullable=True),
        sa.Column("x", sa.Float(), nullable=True),
        sa.Column("y", sa.Float(), nullable=True),
        sa.Column("u", sa.Float(), nullable=True),
        sa.Column("v", sa.Float(), nullable=True),
        sa.Column("grid_x", sa.Integer(), nullable=True),
        sa.Column("grid_y", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.match_id"],
        ),
        sa.ForeignKeyConstraint(
            ["steamid"],
            ["players.steamid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("player_map_events", schema=None) as batch_op:
        batch_op.create_index("idx_pme_lookup", ["steamid", "map", "event_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_player_map_events_match_id"), ["match_id"], unique=False
        )

    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ingested_by_steamid", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            "fk_matches_ingested_by_steamid_players",
            "players",
            ["ingested_by_steamid"],
            ["steamid"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.drop_constraint("fk_matches_ingested_by_steamid_players", type_="foreignkey")
        batch_op.drop_column("ingested_by_steamid")

    with op.batch_alter_table("player_map_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_player_map_events_match_id"))
        batch_op.drop_index("idx_pme_lookup")

    op.drop_table("player_map_events")
    with op.batch_alter_table("grenades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_grenades_match_id"))

    op.drop_table("grenades")
    with op.batch_alter_table("blinds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blinds_match_id"))

    op.drop_table("blinds")
    op.drop_table("users")
    op.drop_table("player_map_zones")
    # ### end Alembic commands ###
