"""add player_clutches table

Revision ID: 592a61f26c6a
Revises: 4d6cde1f551d
Create Date: 2026-07-15 04:42:54.400532
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "592a61f26c6a"
down_revision: str | None = "4d6cde1f551d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_clutches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("steamid", sa.String(), nullable=False),
        sa.Column("round_num", sa.Integer(), nullable=False),
        sa.Column("enemies_at_start", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.match_id"],
        ),
        sa.ForeignKeyConstraint(
            ["steamid"],
            ["players.steamid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("player_clutches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_player_clutches_match_id"), ["match_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_player_clutches_steamid"), ["steamid"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_clutches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_player_clutches_steamid"))
        batch_op.drop_index(batch_op.f("ix_player_clutches_match_id"))

    op.drop_table("player_clutches")
    # ### end Alembic commands ###
