"""add kast a player_match_stats

Revision ID: 730e86c3d99e
Revises: 0ed19b7a686e
Create Date: 2026-07-13 19:42:27.548460
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "730e86c3d99e"
down_revision: str | None = "0ed19b7a686e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_match_stats", schema=None) as batch_op:
        batch_op.add_column(sa.Column("kast", sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_match_stats", schema=None) as batch_op:
        batch_op.drop_column("kast")

    # ### end Alembic commands ###
