"""add lineups table

Revision ID: 95aae2fd3fc6
Revises: e8dc6a57aaf2
Create Date: 2026-08-06 20:42:20.549103
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "95aae2fd3fc6"
down_revision: str | None = "e8dc6a57aaf2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lineups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("map", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("team", sa.String(), nullable=True),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("start_x", sa.Float(), nullable=True),
        sa.Column("start_y", sa.Float(), nullable=True),
        sa.Column("video_url", sa.String(), nullable=False),
        sa.Column("instructions", sa.String(), nullable=True),
        sa.Column("crosshair_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lineups", schema=None) as batch_op:
        batch_op.create_index("idx_lineups_map", ["map"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lineups", schema=None) as batch_op:
        batch_op.drop_index("idx_lineups_map")

    op.drop_table("lineups")
    # ### end Alembic commands ###
