"""fase2: entry multikills clutches

Revision ID: 9b8e994770af
Revises: 730e86c3d99e
Create Date: 2026-07-13 19:47:24.072765
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9b8e994770af"
down_revision: str | None = "730e86c3d99e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_match_stats", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entry_kills", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("entry_deaths", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("k2", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("k3", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("k4", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("k5", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("clutches", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_match_stats", schema=None) as batch_op:
        batch_op.drop_column("clutches")
        batch_op.drop_column("k5")
        batch_op.drop_column("k4")
        batch_op.drop_column("k3")
        batch_op.drop_column("k2")
        batch_op.drop_column("entry_deaths")
        batch_op.drop_column("entry_kills")

    # ### end Alembic commands ###
