"""add seconds_into_round to player_map_events

Revision ID: ddedba0a290d
Revises: 592a61f26c6a
Create Date: 2026-07-15 04:58:38.133796
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ddedba0a290d"
down_revision: str | None = "592a61f26c6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_map_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("seconds_into_round", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_map_events", schema=None) as batch_op:
        batch_op.drop_column("seconds_into_round")

    # ### end Alembic commands ###
