"""add totp and backup codes

Revision ID: e8dc6a57aaf2
Revises: cf291c359c33
Create Date: 2026-08-06 11:52:41.908096
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e8dc6a57aaf2"
down_revision: str | None = "cf291c359c33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "totp_backup_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("steamid", sa.String(), nullable=False),
        sa.Column("code_hash", sa.String(), nullable=False),
        sa.Column("used_at", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["steamid"], ["users.steamid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("totp_backup_codes", schema=None) as batch_op:
        batch_op.create_index("idx_totp_backup_steamid", ["steamid"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("totp_secret", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("totp_enabled_at", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("totp_failed_attempts", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("totp_locked_until", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("totp_locked_until")
        batch_op.drop_column("totp_failed_attempts")
        batch_op.drop_column("totp_enabled_at")
        batch_op.drop_column("totp_secret")

    with op.batch_alter_table("totp_backup_codes", schema=None) as batch_op:
        batch_op.drop_index("idx_totp_backup_steamid")

    op.drop_table("totp_backup_codes")
    # ### end Alembic commands ###
