"""rate limiting: tabla rate_limit_buckets + session_epoch/lockout en users
y account_signups

Revision ID: f00cb11147dc
Revises: d8e1f4b7c3a5
Create Date: 2026-08-06 11:14:04.636469
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f00cb11147dc"
down_revision: str | None = "d8e1f4b7c3a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_buckets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("window_start", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rate_limit_buckets", schema=None) as batch_op:
        batch_op.create_index("idx_rate_limit_scope_key", ["scope", "key"], unique=False)
        batch_op.create_index(
            "uq_rate_limit_scope_key_window", ["scope", "key", "window_start"], unique=True
        )

    # server_default="0" en las columnas NOT NULL: hay filas existentes en
    # users/account_signups, así que el ADD COLUMN necesita un default para
    # no romper contra una tabla poblada.
    with op.batch_alter_table("account_signups", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("failed_login_attempts", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("locked_until", sa.String(), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("session_epoch", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column("failed_login_attempts", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("locked_until", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("locked_until")
        batch_op.drop_column("failed_login_attempts")
        batch_op.drop_column("session_epoch")

    with op.batch_alter_table("account_signups", schema=None) as batch_op:
        batch_op.drop_column("locked_until")
        batch_op.drop_column("failed_login_attempts")

    with op.batch_alter_table("rate_limit_buckets", schema=None) as batch_op:
        batch_op.drop_index("uq_rate_limit_scope_key_window")
        batch_op.drop_index("idx_rate_limit_scope_key")

    op.drop_table("rate_limit_buckets")
    # ### end Alembic commands ###
